version: '2'
services:
    dev:
        ports:
            - "127.0.0.1:8889:8888"
        build:
            context: .
            dockerfile: Dockerfile.dev
            args:
                PROJECT_DIR: ${PWD}
        environment:
            DOTNET_RUNNING_IN_CONTAINER: 1
            DOTNET_USE_POLLING_FILE_WATCHER: 1
            NUGET_PACKAGES: ${PWD}/nuget
        volumes:
            - .:${PWD}
        command: bash -c 'dotnet watch --project src run'
        depends_on:
            - redis

    prod:
        ports:
            - "127.0.0.1:8888:8888"
        build:
            context: .
            dockerfile: Dockerfile.prod
        depends_on:
            - redis

    redis:
        image: 'redis'

    fsharp-language-server:
        volumes:
            - .:${PWD}
        build:
            context: .
            args:
                PROJECT_DIR: ${PWD}
        command: 'bash -c fls'
        environment:
            - NUGET_PACKAGES=${PWD}/nuget
